### PR TITLE
DCTCP example clean up

### PR DESCRIPTION
**Pull request by Vivek-anand-jain**
Please verify the results before merging.

### CODE REVIEW

**Comment by Vivek-anand-jain** [comment]
Hi Shikha,

Could you please verify this PR?

**Comment by ShikhaBakshi** [comment]
Hi Vivek,

I am reviewing the PR. One correction which I found is that in the function for Cwndchange; we need to divide the newCwnd by 1446.

**Review by ShikhaBakshi — COMMENTED** [review]
Hi Vivek,

I am reviewing the PR. One correction which I found is that in the function for CwndChange; we need to divide the newCwnd by 1446.0

**Comment by Vivek-anand-jain** [comment]
Hi Shikha,

Have you tested this PR after applying the listed correction?

**Pull request merged**
